base_url = "https://scratchx98.github.io"

title = "ScratchX98"
description = "A simple personal website"

theme = "serene"

compile_sass = true
minify_html = false

generate_feed = false

[markdown]
highlight_code = true
highlight_theme = "two-dark"
render_emoji = true
external_links_target_blank = true

[extra]
name = "ScratchX"
id = "ScratchX98"
bio = "Dart, Rust, and PHP"

show_projects = true

links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/ScratchX98"},
    {name = "Reddit", icon = "ri-reddit-line", url = "https://reddit.com/u/scratchx98"},
    {name = "Discord", icon = "ri-discord-line", url = "https://discordapp.com/users/620090816140148736"},
    {name = "StackOverflow", icon = "ri-stack-overflow-line", url = "https://stackoverflow.com/users/17331482/scratchx"},
    {name = "Email", icon = "ri-mail-line", url = "mailto:scratchx@gmx.com"},
]

footer_custom = "Made by ScratchX98"
footer_credits = true

feed_in_blog_section = false

blog_icon = "ri-quill-pen-line"          
projects_icon = "ri-compasses-2-line"
home_icon = "ri-user-6-line"
rss_icon = "ri-rss-line"
toc_icon = "ri-menu-2-line"
notes_icon = "ri-booklet-line"

blur_effect = false

analytics = "google_analytics"
[extra.google_analytics]
id = "G-YTQDWNXD13"
